### ISSUE TITLE
找不到字体

### ISSUE THREAD

**Issue by maxwell652** [alwaysmy/pyocd_GUI#1]
是不是还需要上传字体
![image](https://github.com/alwaysmy/pyocd_GUI/assets/23316609/2141e719-7400-4bbf-a4ce-88062da7f01e)

**Comment by maxwell652** [comment]
另外，自己添加字体后，发布exe，运行也有报错，你知道是哪里出错了吗
![image](https://github.com/alwaysmy/pyocd_GUI/assets/23316609/c8209d4f-bb18-4ec8-89d8-7b916c4d074f)

**Comment by alwaysmy** [comment]
哦我搞忘记这一点了，直接安装[德意黑字体](https://github.com/atelier-anchor/smiley-sans)到系统后编译即可。

如果你不想用这个字体，去掉代码中对字体的包含，
就是这一段：
```
namespace fonts.德意黑{ 
    family = ..fonts.addFamily($"~/lib/fonts/.res/得意黑.ttf") 
}
```
然后修改用到这个字体的控件的字体选项就好了，我这里只有擦除和下载两个按键用了。
![image](https://github.com/alwaysmy/pyocd_GUI/assets/39006423/410b3fcd-1a1b-4826-941d-6f1aa943e907)

**Comment by alwaysmy** [comment]
> 另外，自己添加字体后，发布exe，运行也有报错，你知道是哪里出错了吗 ![image](https://user-images.githubusercontent.com/23316609/262064071-c8209d4f-bb18-4ec8-89d8-7b916c4d074f.png)

这个看起来不是字体的问题，我没有触发过这个错误，可以告知一下你安装的pyocd版本是什么还有你手工执行pyocd list命令后显示什么吗（截个图），用我发布的exe也会出现同样的错误吗

**Comment by maxwell652** [comment]
> > 另外，自己添加字体后，发布exe，运行也有报错，你知道是哪里出错了吗 ![image](https://user-images.githubusercontent.com/23316609/262064071-c8209d4f-bb18-4ec8-89d8-7b916c4d074f.png)
> 
> 这个看起来不是字体的问题，我没有触发过这个错误，可以告知一下你安装的pyocd版本是什么还有你手工执行pyocd list命令后显示什么吗（截个图），用我发布的exe也会出现同样的错误吗

用你打包的那个没啥问题，可能是我自己电脑环境的原因，我再看看
